management.endpoint.env.enabled: false

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        descriptions: true
        enabled: true
        step: '1m'

spring:
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    url: jdbc:h2:file:/data/data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

kafka:
  bootstrapAddress: localhost:9092
