apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}-${TRAVIS_BRANCH}
  #namespace: services
  labels:
    app: "${SERVICE_NAME}-${TRAVIS_BRANCH}"
    chatChannel: "${TRAVIS_BRANCH}"
    serviceVersion: "${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}"
    event: "CodeCamp"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "${SERVICE_NAME}-${TRAVIS_BRANCH}"
      chatChannel: "${TRAVIS_BRANCH}"
      event: "CodeCamp"
  template:
    metadata:
      #namespace: services
      labels:
        app: "${SERVICE_NAME}-${TRAVIS_BRANCH}"
        chatChannel: "${TRAVIS_BRANCH}"
        serviceVersion: "${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}"
        event: "CodeCamp"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
    spec:
      containers:
        - name: ${SERVICE_NAME}-${TRAVIS_BRANCH}
          image: eu.gcr.io/code-and-play/${DOCKER_IMAGE}
          imagePullPolicy: IfNotPresent
          env:
          - name: SERVICE_CHANNEL
            value: ${TRAVIS_BRANCH}
          ports:
          - name: http
            containerPort: 8080
          volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: db-data
            mountPath: /data
      volumes:
      - name: tmp
        emptyDir: {}
      - name: db-data
        emptyDir: {}
